// this is a read only file generated by manual inputs to file mustache/templates/rates/contracts.js.
export let contractsToInstances = new Map<string, string>();
contractsToInstances.set("0x785d7a0de8b7813033452c9d6dbc86a5238927fc", // Instance-bnb-0.1
  "bnb-0.1"
);
contractsToInstances.set("0x8d149a2f7903bb0341cf3f05b199a8f7a7f7ecc9", // Instance-bnb-1
  "bnb-1"
);
contractsToInstances.set("0x6eee950366adc89c441b8cd80503b1974f419da7", // Instance-bnb-10
  "bnb-10"
);
contractsToInstances.set("0xb9b3877b1ad881645ff372fd7b7cb788de8243bc", // Instance-bnb-100
  "bnb-100"
);
contractsToInstances.set("0xb8cc42c43bec92b305d4850c4d64818fb275919a", // Instance-storm-10
  "storm-10"
);
contractsToInstances.set("0x4e70f58fb952f65235db0cef641ac71c44434cd4", // Instance-storm-100
  "storm-100"
);
contractsToInstances.set("0x7242ca65719710f0f9c00977ee9938fda21cb38c", // Instance-storm-500
  "storm-500"
);
contractsToInstances.set("0x53bd8f43b4468c8d963c81cdd61ee5a2d4c91631", // Instance-storm-1000
  "storm-1000"
);
contractsToInstances.set("0x9c3c7f40112eedfaaa42441054d7f4f5b8387d6f", // Instance-busd-10
  "busd-10"
);
contractsToInstances.set("0x8464fa0ad92fe1b07b1f5ad5a5299f3990942c88", // Instance-busd-100
  "busd-100"
);
contractsToInstances.set("0xbb77170f1f9d7d8a4f8cd6caa1648be06abab087", // Instance-busd-1000
  "busd-1000"
);
contractsToInstances.set("0xb8dee638c3743384558656987dd7dacac542daa1", // Instance-busd-10000
  "busd-10000"
);
contractsToInstances.set("0x1e34a77868e19a6647b1f2f47b51ed72dede95dd", // Instance-xdai-100
  "xdai-100"
);
contractsToInstances.set("0xdf231d99ff8b6c6cbf4e9b9a945cbacef9339178", // Instance-xdai-1000
  "xdai-1000"
);
contractsToInstances.set("0xaf4c0b70b2ea9fb7487c7cbb37ada259579fe040", // Instance-xdai-10000
  "xdai-10000"
);
contractsToInstances.set("0xa5c2254e4253490c54cef0a4347fddb8f75a4998", // Instance-xdai-100000
  "xdai-100000"
);
contractsToInstances.set("0x1e34a77868e19a6647b1f2f47b51ed72dede95dd", // Instance-matic-100
  "matic-100"
);
contractsToInstances.set("0xdf231d99ff8b6c6cbf4e9b9a945cbacef9339178", // Instance-matic-1000
  "matic-1000"
);
contractsToInstances.set("0xaf4c0b70b2ea9fb7487c7cbb37ada259579fe040", // Instance-matic-10000
  "matic-10000"
);
contractsToInstances.set("0xa5c2254e4253490c54cef0a4347fddb8f75a4998", // Instance-matic-100000
  "matic-100000"
);
contractsToInstances.set("0x654ea9db6792569bd276fe862748b9d67afaa002", // Instance-eth-0.1
  "eth-0.1"
);
contractsToInstances.set("0x7c133d39220877a781fe2905cd7666e6b6e162aa", // Instance-eth-1
  "eth-1"
);
contractsToInstances.set("0xd545a432855ab48f722f47d2833569fb5f48bf5f", // Instance-eth-10
  "eth-10"
);
contractsToInstances.set("0x753050049ba2e2869ad652c3e6d2ba68854c9086", // Instance-eth-100
  "eth-100"
);
contractsToInstances.set("0xe871436b8e0e69934e8f7237a07d7b06d7ca5ff7", // Instance-dai-100
  "dai-100"
);
contractsToInstances.set("0xf0f16d32f3af84ae46245e490bedf1b0edf785ec", // Instance-dai-1000
  "dai-1000"
);
contractsToInstances.set("0x7083377d0cf8852358dd6a559281c7c09366887d", // Instance-dai-10000
  "dai-10000"
);
contractsToInstances.set("0x6bf81db7469a0bacb4a14f2cf0a70c7af8be2ff8", // Instance-dai-100000
  "dai-100000"
);
contractsToInstances.set("0x1fcde12aab9bde309019adf18b36c9aa66bd9e81", // Instance-hex-100
  "hex-100"
);
contractsToInstances.set("0x4e2bd6c44813ec175c6666a2a615a8f05854ce91", // Instance-hex-1000
  "hex-1000"
);
contractsToInstances.set("0x11a99a832d6615209fcb79125e5ef629a92f6c05", // Instance-hex-10000
  "hex-10000"
);
contractsToInstances.set("0x4e09ee0f4230bb259f361ddf031ed075a32b34d6", // Instance-hex-100000
  "hex-100000"
);
contractsToInstances.set("0x76d85b4c0fc497eecc38902397ac608000a06607", // Instance-dai-100
  "dai-100"
);
contractsToInstances.set("0xcc84179ffd19a1627e79f8648d09e095252bc418", // Instance-dai-1000
  "dai-1000"
);
contractsToInstances.set("0xd5d6f8d9e784d0e26222ad3834500801a68d027d", // Instance-dai-10000
  "dai-10000"
);
contractsToInstances.set("0x407cceeaa7c95d2fe2250bf9f2c105aa7aafb512", // Instance-dai-100000
  "dai-100000"
);
contractsToInstances.set("0x833481186f16cece3f1eeea1a694c42034c3a0db", // Instance-cdai-5000
  "cdai-5000"
);
contractsToInstances.set("0xd8d7de3349ccaa0fde6298fe6d7b7d0d34586193", // Instance-cdai-50000
  "cdai-50000"
);
contractsToInstances.set("0x8281aa6795ade17c8973e1aedca380258bc124f9", // Instance-cdai-500000
  "cdai-500000"
);
contractsToInstances.set("0x57b2b8c82f065de8ef5573f9730fc1449b403c9f", // Instance-cdai-5000000
  "cdai-5000000"
);
contractsToInstances.set("0x05e0b5b40b7b66098c2161a5ee11c5740a3a7c45", // Instance-usdc-100
  "usdc-100"
);
contractsToInstances.set("0x23173fe8b96a4ad8d2e17fb83ea5dcccdca1ae52", // Instance-usdc-1000
  "usdc-1000"
);
contractsToInstances.set("0x538ab61e8a9fc1b2f93b3dd9011d662d89be6fe6", // Instance-usdt-100
  "usdt-100"
);
contractsToInstances.set("0x94be88213a387e992dd87de56950a9aef34b9448", // Instance-usdt-1000
  "usdt-1000"
);
contractsToInstances.set("0x242654336ca2205714071898f67e254eb49acdce", // Instance-wbtc-0.1
  "wbtc-0.1"
);
contractsToInstances.set("0x776198ccf446dfa168347089d7338879273172cf", // Instance-wbtc-1
  "wbtc-1"
);
contractsToInstances.set("0xedc5d01286f99a066559f60a585406f3878a033e", // Instance-wbtc-10
  "wbtc-10"
);
contractsToInstances.set("0x6bf694a291df3fec1f7e69701e3ab6c592435ae7", // Instance-eth-0.1
  "eth-0.1"
);
contractsToInstances.set("0x3aac1cc67c2ec5db4ea850957b967ba153ad6279", // Instance-eth-1
  "eth-1"
);
contractsToInstances.set("0x723b78e67497e85279cb204544566f4dc5d2aca0", // Instance-eth-10
  "eth-10"
);
contractsToInstances.set("0x0e3a09dda6b20afbb34ac7cd4a6881493f3e7bf7", // Instance-eth-100
  "eth-100"
);
contractsToInstances.set("0x330bdfade01ee9bf63c209ee33102dd334618e0a", // Instance-avax-10
  "avax-10"
);
contractsToInstances.set("0x1e34a77868e19a6647b1f2f47b51ed72dede95dd", // Instance-avax-100
  "avax-100"
);
contractsToInstances.set("0xaf8d1839c3c67cf571aa74b5c12398d4901147b3", // Instance-avax-500
  "avax-500"
);
contractsToInstances.set("0x84443cfd09a48af6ef360c6976c5392ac5023a1f", // Instance-eth-0.1
  "eth-0.1"
);
contractsToInstances.set("0xd47438c816c9e7f2e2888e060936a499af9582b3", // Instance-eth-1
  "eth-1"
);
contractsToInstances.set("0x330bdfade01ee9bf63c209ee33102dd334618e0a", // Instance-eth-10
  "eth-10"
);
contractsToInstances.set("0x1e34a77868e19a6647b1f2f47b51ed72dede95dd", // Instance-eth-100
  "eth-100"
);
contractsToInstances.set("0x84443cfd09a48af6ef360c6976c5392ac5023a1f", // Instance-eth-0.1
  "eth-0.1"
);
contractsToInstances.set("0xd47438c816c9e7f2e2888e060936a499af9582b3", // Instance-eth-1
  "eth-1"
);
contractsToInstances.set("0x330bdfade01ee9bf63c209ee33102dd334618e0a", // Instance-eth-10
  "eth-10"
);
contractsToInstances.set("0x1e34a77868e19a6647b1f2f47b51ed72dede95dd", // Instance-eth-100
  "eth-100"
);
// this is a read only file generated by manual inputs to file mustache/templates/rates/contracts.js.
